ALTER TYPE "InquiryStatus" ADD VALUE IF NOT EXISTS 'INSPECTION_BOOKED';
ALTER TYPE "InquiryStatus" ADD VALUE IF NOT EXISTS 'CONVERTED';

ALTER TYPE "InspectionStatus" ADD VALUE IF NOT EXISTS 'REQUESTED';
ALTER TYPE "InspectionStatus" ADD VALUE IF NOT EXISTS 'RESCHEDULED';

ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INQUIRY_ASSIGNED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INSPECTION_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'KYC_REVIEWED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'RECEIPT_AVAILABLE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INSTALLMENT_DUE';

ALTER TABLE "InspectionBooking"
ADD COLUMN IF NOT EXISTS "assignedStaffId" TEXT,
ADD COLUMN IF NOT EXISTS "userId" TEXT;

CREATE INDEX IF NOT EXISTS "InspectionBooking_companyId_assignedStaffId_status_idx"
ON "InspectionBooking"("companyId", "assignedStaffId", "status");

DO $$
BEGIN
  ALTER TABLE "InspectionBooking"
  ADD CONSTRAINT "InspectionBooking_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE "InspectionBooking"
  ADD CONSTRAINT "InspectionBooking_assignedStaffId_fkey"
  FOREIGN KEY ("assignedStaffId") REFERENCES "StaffProfile"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
