import type { PropertySummary } from "@/types/domain";

export const properties: PropertySummary[] = [
  {
    id: "prop-eko-atrium",
    slug: "eko-atrium-residences",
    title: "Eko Atrium Residences",
    shortDescription: "Lagos waterfront apartments built for buyers who expect privacy, elegance, and dependable delivery.",
    description:
      "Eko Atrium Residences is a premium mixed-use development designed for discerning buyers seeking a calm ownership experience with transparent milestones, structured payment plans, and concierge-level service from reservation to handover.",
    type: "Apartment",
    status: "available",
    featured: true,
    priceFrom: 185000000,
    priceTo: 265000000,
    bedrooms: 3,
    bathrooms: 3,
    parkingSpaces: 2,
    sizeSqm: 214,
    locationSummary: "Oniru, Victoria Island, Lagos",
    city: "Lagos",
    state: "Lagos",
    coordinates: [3.447, 6.431],
    images: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=1200&q=80",
    ],
    paymentPlan: {
      title: "18-Month Structured Plan",
      summary: "30% initial deposit, quarterly milestone payments, and protected allocation workflow.",
      durationMonths: 18,
      depositPercent: 30,
    },
    features: [
      "Private residents lounge",
      "Smart access control",
      "Dedicated facility management",
      "24/7 power and water",
      "Gym and rooftop terrace",
    ],
    landmarks: ["Landmark Beach", "The Delborough", "Eko Hotel", "British International School"],
    brochureName: "eko-atrium-brochure.pdf",
    inquiryCount: 42,
    verification: {
      status: "VERIFIED",
      label: "Verified 2 days ago",
      detail: "Next verification due Apr 07, 2026.",
      tone: "success",
      isPubliclyVisible: true,
      lastVerifiedAt: "2026-03-31T09:00:00.000Z",
      verificationDueAt: "2026-04-07T09:00:00.000Z",
    },
  },
  {
    id: "prop-ikoyi-gardens",
    slug: "ikoyi-garden-villas",
    title: "Ikoyi Garden Villas",
    shortDescription: "Private villa enclave for high-net-worth families seeking long-term value and smooth transaction execution.",
    description:
      "Ikoyi Garden Villas combines a low-density estate plan with disciplined legal, payment, and client success operations so buyers move from inspection to completion with less uncertainty and better visibility.",
    type: "Detached",
    status: "reserved",
    featured: true,
    priceFrom: 420000000,
    bedrooms: 5,
    bathrooms: 5,
    parkingSpaces: 4,
    sizeSqm: 486,
    locationSummary: "Bourdillon Axis, Ikoyi, Lagos",
    city: "Lagos",
    state: "Lagos",
    coordinates: [3.4365, 6.4544],
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1560185008-a33f5c7d4c0a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    ],
    paymentPlan: {
      title: "12-Month Capital Plan",
      summary: "40% commitment deposit with milestone-based disbursement.",
      durationMonths: 12,
      depositPercent: 40,
    },
    features: [
      "Private cinema room",
      "Family pool deck",
      "Backup power plant",
      "Estate surveillance",
      "Home automation pre-install",
    ],
    landmarks: ["Lagos Polo Club", "Murtala Mohammed Park", "Ikoyi Club"],
    brochureName: "ikoyi-garden-villas.pdf",
    inquiryCount: 19,
    verification: {
      status: "STALE",
      label: "Last updated 14 days ago",
      detail: "This listing is stale. Buyers can still view it, but admins should re-verify it soon.",
      tone: "warning",
      isPubliclyVisible: true,
      lastVerifiedAt: "2026-03-19T09:00:00.000Z",
      verificationDueAt: "2026-03-26T09:00:00.000Z",
    },
  },
  {
    id: "prop-abuja-rise",
    slug: "asokoro-rise-terraces",
    title: "Asokoro Rise Terraces",
    shortDescription: "A diplomatic district terrace cluster with strong title profile and measured installment planning.",
    description:
      "Asokoro Rise Terraces is built for professionals and diaspora buyers who need confidence in title, documentation, payment clarity, and post-sale support. The platform foundation models that full journey from inquiry to handover.",
    type: "Terrace",
    status: "sold",
    featured: false,
    priceFrom: 96000000,
    bedrooms: 4,
    bathrooms: 4,
    parkingSpaces: 2,
    sizeSqm: 182,
    locationSummary: "Asokoro Extension, Abuja",
    city: "Abuja",
    state: "FCT",
    coordinates: [7.536, 9.0579],
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=80",
    ],
    paymentPlan: {
      title: "Outright or 6-Month Completion Plan",
      summary: "Reserved inventory closed out; sold units retained for trust-building proof.",
      durationMonths: 6,
      depositPercent: 50,
    },
    features: [
      "BQ option",
      "Dedicated estate management",
      "Children play court",
      "Water treatment system",
      "Secure access gate",
    ],
    landmarks: ["Aso Rock", "Transcorp Hilton", "ICRC Headquarters"],
    brochureName: "asokoro-rise-terraces.pdf",
    inquiryCount: 57,
    verification: {
      status: "VERIFIED",
      label: "Verified 5 days ago",
      detail: "Next verification due Apr 04, 2026.",
      tone: "success",
      isPubliclyVisible: true,
      lastVerifiedAt: "2026-03-28T09:00:00.000Z",
      verificationDueAt: "2026-04-04T09:00:00.000Z",
    },
  },
];

export function getPropertyBySlug(slug: string) {
  return properties.find((property) => property.slug === slug);
}
