// GENERATED FILE, DO NOT EDIT BY HAND.
// Regenerate with: node scripts/generate-migration-manifest.mjs
//
// Every migration directory in prisma/migrations, used by the readiness
// endpoint to detect a database that is behind the deployed code. Generated
// so the list can never silently go stale (see the script header for the
// production incident that motivated this).

export const EXPECTED_PRODUCTION_MIGRATIONS = [
  "0001_init",
  "0002_billing_monetization",
  "0003_team_marketers_payment_progress",
  "0004_crm_inspections_notifications",
  "0005_staff_directory_id_cards",
  "0006_wishlist_crm_intelligence",
  "0007_property_verification_trust_layer",
  "0008_operating_system_dashboard_and_automation",
  "0009_payment_requests_and_verification_runtime",
  "0010_tenant_branding_workflow",
  "0011_marketer_relations_and_snapshots",
  "0012_activation_and_collections_follow_up",
  "0013_collections_priority_and_quick_actions",
  "0014_company_lifecycle_realtime_analytics",
  "0015_development_feasibility_calculator",
  "0016_development_calculation_phasing",
  "0017_development_calculation_versioning",
  "0018_deal_risk_scoring",
  "0019_support_requests_linear",
  "0020_support_request_retry_metadata",
  "0021_support_sync_backoff_and_revenue_snapshot",
  "0022_incident_aggregation_and_escalation",
  "0023_incident_windows_cooldown_and_resolution",
  "0024_incident_pruning_caching_and_linear_updates",
  "0025_buyer_profile_image",
  "0026_development_decision_status",
  "0027_property_land_options_countdown",
  "0028_property_global_land_units",
  "0029_whatsapp_usage_logs",
  "0030_communication_wallet_ledger",
  "0031_communication_topups",
  "0032_buyer_portal_kyc_review_metadata",
  "0033_buyer_testimonial_moderation",
  "0034_contract_generation_mvp",
  "0035_contract_template_version_locking",
  "0035a_team_member_invitation_base",
  "0036_team_invitation_branch",
  "0037_property_location_mapbox",
  "0038_property_location_boundary",
  "0039_team_invitation_invited_by_user_id",
  "0040_drop_legacy_team_invitation_invited_by_id",
  "0041_sync_schema_drift",
  "0042_site_content_cms",
  "0043_team_member_staff_code_unique",
  "0044_front_desk_visitor_call_log",
  "0045_property_invoices",
  "0046_in_app_messaging",
  "0047_announcements",
  "0048_marketer_role",
  "0049_webhook_event_dedup_unique",
  "20260701000111_applies_migration_0044_regenerates_the_prisma_client",
] as const;
